[window]
decorations = "none"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.95

[window.padding]
x = 10
y = 10

[font]
size = 8

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#0f111a"
foreground = "#d0d0d0"

[colors.normal]
black   = "#1c1c1c"
red     = "#ff5c57"
green   = "#5af78e"
yellow  = "#f3f99d"
blue    = "#57c7ff"
magenta = "#ff6ac1"
cyan    = "#9aedfe"
white   = "#f1f1f0"

[colors.bright]
black   = "#686868"
red     = "#ff5c57"
green   = "#5af78e"
yellow  = "#f3f99d"
blue    = "#57c7ff"
magenta = "#ff6ac1"
cyan    = "#9aedfe"
white   = "#ffffff"

[cursor.style]
shape = "Beam"

[terminal.shell]
program = "/bin/bash"
args = ["--login"]

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[terminal]

