#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# i3 dir
idir="$HOME/.config/i3"

# Export desktop session
export XDG_CURRENT_DESKTOP='i3'

# Kill already running process
_ps=(xsettingsd ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch xsettingsd daemon
xsettingsd --config="$idir"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
hsetroot -cover "$idir"/theme/wallpaper

# Lauch notification daemon
"$idir"/scripts/i3_dunst

# Lauch polybar
"$idir"/scripts/i3_bar

# Lauch compositor
"$idir"/scripts/i3_comp

# Start mpd
exec mpd &

# Keyboard layout
setxkbmap -layout us,cz -option grp:switch





# Start Spotify and Discord
i3-msg 'workspace 11; exec vesktop' 
i3-msg 'workspace 12; exec spotify' 


sleep 2 && xrandr --output DP-4 --right-of HDMI-0 && xrandr --output DP-4 --primary

# Restore wallpaper
hsetroot -cover "$idir"/theme/wallpaper


i3-autolayout autolayout
redshift -l 50.0283858:14.4722089
