#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script to manage brightness on Archcraft using xbacklight.

# Icons
iDIR='/usr/share/archcraft/icons/dunst'

# Get brightness
get_backlight() {
    BNESS=$(xbacklight -get)
    LIGHT=${BNESS%.*}
    echo "${LIGHT}%"
}

# Get icons
get_icon() {
    backlight="$(get_backlight)"
    current="${backlight%%%}"
    if [[ "$current" -ge 0 && "$current" -le 20 ]]; then
        icon="$iDIR/brightness-20.png"
    elif [[ "$current" -gt 20 && "$current" -le 40 ]]; then
        icon="$iDIR/brightness-40.png"
    elif [[ "$current" -gt 40 && "$current" -le 60 ]]; then
        icon="$iDIR/brightness-60.png"
    elif [[ "$current" -gt 60 && "$current" -le 80 ]]; then
        icon="$iDIR/brightness-80.png"
    elif [[ "$current" -gt 80 && "$current" -le 100 ]]; then
        icon="$iDIR/brightness-100.png"
    fi
}

# Notify 
notify_bl() {
    get_icon
    dunstify -u low -h string:x-dunst-stack-tag:obbacklight -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
    xbacklight -inc 10
    notify_bl
}

# Decrease brightness
dec_backlight() {
    xbacklight -dec 10
    notify_bl
}

# Execute accordingly
case "$1" in
    --get) get_backlight ;;
    --inc) inc_backlight ;;
    --dec) dec_backlight ;;
    *) get_backlight ;;
esac
